#!/usr/bin/env bash
# Deploy Worker (API + /cdn) and Pages (dashboard).
# Pages: must run from ../pages (no --config — Pages rejects custom wrangler paths).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib-env.sh
source "$SCRIPT_DIR/lib-env.sh"

load_dev_vars
require_npx
cd "$ROOT"

export CLOUDFLARE_API_TOKEN
export CLOUDFLARE_ACCOUNT_ID

PAGES_DIR="$(cd "$ROOT/../pages" && pwd)"
PAGES_PROJECT="vibequant-web"

echo "VibeQuant deploy"
echo "================"
echo ""

set_toml_account_id "$WRANGLER_TOML" "$CLOUDFLARE_ACCOUNT_ID"
ensure_d1_database_id "vibequant" || exit 1

echo "1) Worker: vibequant-api (D1 + R2 + /cdn)"
WORKER_LOG="$(mktemp)"
set +e
wrangler deploy --config "$WRANGLER_TOML" 2>&1 | tee "$WORKER_LOG"
WORKER_RC=${PIPESTATUS[0]}
set -e
if [[ $WORKER_RC -ne 0 ]]; then
  rm -f "$WORKER_LOG"
  exit "$WORKER_RC"
fi

# Prefer env, else parse workers.dev URL from deploy log
DETECTED_API="$(grep -Eo 'https://vibequant-api[^[:space:]]+\.workers\.dev' "$WORKER_LOG" | head -1 || true)"
rm -f "$WORKER_LOG"

API_BASE="${VIBEQUANT_API_BASE:-}"
if [[ -z "$API_BASE" || "$API_BASE" == *"YOUR_SUBDOMAIN"* || "$API_BASE" == *"<"* ]]; then
  API_BASE="$DETECTED_API"
fi
if [[ -z "$API_BASE" ]]; then
  echo "error: could not determine Worker URL. Set VIBEQUANT_API_BASE to the real workers.dev URL." >&2
  exit 1
fi
CDN_BASE="${VIBEQUANT_CDN_BASE:-}"
if [[ -z "$CDN_BASE" || "$CDN_BASE" == *"YOUR_SUBDOMAIN"* ]]; then
  CDN_BASE="${API_BASE%/}/cdn"
fi

export VIBEQUANT_API_BASE="$API_BASE"
export VIBEQUANT_CDN_BASE="$CDN_BASE"
echo "   Worker URL: $API_BASE"
echo ""

echo "2) Pages runtime config"
python3 - <<PY
import json, os
api = os.environ["VIBEQUANT_API_BASE"]
cdn = os.environ["VIBEQUANT_CDN_BASE"]
path = "$PAGES_DIR/js/runtime-config.js"
cfg = {"VIBEQUANT_API_BASE": api, "VIBEQUANT_CDN_BASE": cdn}
with open(path, "w", encoding="utf-8") as f:
    f.write("/* generated by cloudflare/scripts/deploy.sh — do not edit by hand */\n")
    f.write(f"window.RUNTIME_CONFIG = {json.dumps(cfg, indent=2)};\n")
    f.write("window.VIBEQUANT_API_BASE = window.RUNTIME_CONFIG.VIBEQUANT_API_BASE;\n")
    f.write("window.VIBEQUANT_CDN_BASE = window.RUNTIME_CONFIG.VIBEQUANT_CDN_BASE;\n")
print(f"   wrote {path}")
print(f"   VIBEQUANT_API_BASE={api!r}")
print(f"   VIBEQUANT_CDN_BASE={cdn!r}")
PY
echo ""

if [[ -n "${SITE_URL:-}" ]]; then
  echo "   SITE_URL=$SITE_URL"
  SITE_URL="$SITE_URL" node "$ROOT/../content/build.mjs"
  echo ""
fi

echo "3) Pages: $PAGES_PROJECT ← $PAGES_DIR"
echo "   (deploy from pages/ — no --config; Pages forbids custom wrangler paths)"
WRANGLER_BIN="$ROOT/node_modules/.bin/wrangler"
(
  cd "$PAGES_DIR"
  if [[ -x "$WRANGLER_BIN" ]]; then
    "$WRANGLER_BIN" pages deploy . \
      --project-name="$PAGES_PROJECT" \
      --commit-dirty=true
  else
    npx --yes wrangler pages deploy . \
      --project-name="$PAGES_PROJECT" \
      --commit-dirty=true
  fi
)

echo ""
echo "Deploy done."
echo "  Worker: $API_BASE"
echo "  CDN:    $CDN_BASE"
echo "  Pages:  https://${PAGES_PROJECT}.pages.dev/"
echo "  Smoke:"
echo "    curl -sS \"$API_BASE/api/health\""
echo "    curl -sS \"$CDN_BASE/tests/hello.txt\""
