#!/usr/bin/env bash
# Deploy Worker (API + /cdn) and Pages (dashboard).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib-env.sh
source "$SCRIPT_DIR/lib-env.sh"

load_dev_vars
require_npx
cd "$ROOT"

export CLOUDFLARE_API_TOKEN
export CLOUDFLARE_ACCOUNT_ID

PAGES_DIR="$(cd "$ROOT/../pages" && pwd)"
PAGES_PROJECT="vibequant-web"

echo "VibeQuant deploy"
echo "================"
echo ""

if grep -q 'REPLACE_WITH_D1_DATABASE_ID' "$WRANGLER_TOML"; then
  echo "error: D1 database_id still placeholder. Run ./scripts/bootstrap.sh first." >&2
  exit 1
fi

echo "1) Worker: vibequant-api (D1 + R2 + /cdn)"
wrangler deploy --config "$WRANGLER_TOML"
echo ""

echo "2) Pages runtime config"
python3 - <<PY
import json, os
api = os.environ.get("VIBEQUANT_API_BASE", "")
cdn = os.environ.get("VIBEQUANT_CDN_BASE", "") or (api.rstrip("/") + "/cdn" if api else "")
path = "$PAGES_DIR/js/runtime-config.js"
with open(path, "w", encoding="utf-8") as f:
    f.write("/* generated by deploy.sh — do not edit by hand */\n")
    f.write(f"window.VIBEQUANT_API_BASE = {json.dumps(api)};\n")
    f.write(f"window.VIBEQUANT_CDN_BASE = {json.dumps(cdn)};\n")
print(f"   wrote {path}")
print(f"   VIBEQUANT_API_BASE={api!r}")
print(f"   VIBEQUANT_CDN_BASE={cdn!r}")
PY

echo "3) Pages: $PAGES_PROJECT ← $PAGES_DIR"
# Must use wrangler.pages.toml — default wrangler.toml is the Worker and lacks pages_build_output_dir
wrangler pages deploy "$PAGES_DIR" \
  --config "$WRANGLER_PAGES" \
  --project-name="$PAGES_PROJECT" \
  --commit-dirty=true

echo ""
echo "Deploy done."
echo "  Optional — bind dashboard to Worker on next deploy:"
echo "    export VIBEQUANT_API_BASE=https://vibequant-api.<subdomain>.workers.dev"
echo "    ./scripts/deploy.sh"
echo "  Smoke:"
echo "    curl -sS \"\$VIBEQUANT_API_BASE/api/health\""
echo "    curl -sS \"\$VIBEQUANT_API_BASE/cdn/tests/hello.txt\""
