#!/usr/bin/env bash
# Interactive secret setup — TOSS API + Cloudflare keys only.
# Usage:
#   ./scripts/setup-secrets.sh --local    # write cloudflare/.dev.vars (chmod 600)
#   ./scripts/setup-secrets.sh --remote   # wrangler secret put (TOSS → Worker)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEV_VARS="$ROOT/.dev.vars"
WRANGLER_TOML="$ROOT/wrangler.toml"
MODE=""

usage() {
  cat <<'EOF'
VibeQuant — secret setup (TOSS API + Cloudflare keys)

  --local   Write .dev.vars for local wrangler / deploy scripts
  --remote  Upload TOSS secrets to the Worker via wrangler
  -h        Show help

Keys collected:
  TOSS_CLIENT_ID / TOSS_CLIENT_SECRET     (optional; Enter to skip)
  CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID   (required for --local deploy)

Notes:
  - Secret values are never printed.
  - Cloudflare API token is for YOUR machine / CI (wrangler auth), not Worker runtime.
  - TOSS secrets are Worker runtime secrets (--remote) or .dev.vars (--local).
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --local)  MODE=local; shift ;;
    --remote) MODE=remote; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

if [[ -z "$MODE" ]]; then
  usage
  exit 1
fi

prompt() {
  local label="$1"
  local var
  read -rp "$label" var
  printf '%s' "$var"
}

prompt_secret() {
  local label="$1"
  local var
  read -rsp "$label" var
  echo "" >&2
  printf '%s' "$var"
}

echo "VibeQuant secrets — TOSS API + Cloudflare"
echo "========================================="
echo ""

# ── TOSS ─────────────────────────────────────────────────
echo "1) TOSS Open API (optional — press Enter to skip / Yahoo-only)"
echo "   https://developers.tossinvest.com"
echo ""
TOSS_ID="$(prompt "   TOSS_CLIENT_ID: ")"
TOSS_SECRET=""
if [[ -n "$TOSS_ID" ]]; then
  TOSS_SECRET="$(prompt_secret "   TOSS_CLIENT_SECRET (hidden): ")"
  if [[ -z "$TOSS_SECRET" ]]; then
    echo "error: TOSS_CLIENT_ID set but TOSS_CLIENT_SECRET empty" >&2
    exit 1
  fi
  echo "   TOSS: configured"
else
  echo "   TOSS: skipped"
fi
echo ""

# ── Cloudflare ───────────────────────────────────────────
echo "2) Cloudflare (API token + account id)"
echo "   Create token: https://dash.cloudflare.com/profile/api-tokens"
echo "   Suggested permissions: Account — Workers Scripts Edit, D1 Edit, R2 Edit,"
echo "                          Account Settings Read"
echo "   Account ID: dashboard → Workers & Pages → Overview (right sidebar)"
echo ""

CF_TOKEN=""
CF_ACCOUNT=""
if [[ "$MODE" == "local" ]]; then
  CF_TOKEN="$(prompt_secret "   CLOUDFLARE_API_TOKEN (hidden): ")"
  CF_ACCOUNT="$(prompt "   CLOUDFLARE_ACCOUNT_ID: ")"
  if [[ -z "$CF_TOKEN" || -z "$CF_ACCOUNT" ]]; then
    echo "error: CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID are required for --local" >&2
    exit 1
  fi
  echo "   Cloudflare: configured"
else
  echo "   --remote: Cloudflare API token stays on this machine (not uploaded as Worker secret)."
  echo "   Ensure CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID are in the environment"
  echo "   or run --local first so .dev.vars exists for wrangler."
  if [[ -f "$DEV_VARS" ]]; then
    # shellcheck disable=SC1090
    set -a
    # Only export known keys from .dev.vars (no eval of arbitrary code)
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      [[ -z "${line// }" ]] && continue
      case "$line" in
        CLOUDFLARE_API_TOKEN=*|CLOUDFLARE_ACCOUNT_ID=*|TOSS_CLIENT_ID=*|TOSS_CLIENT_SECRET=*)
          export "$line"
          ;;
      esac
    done < "$DEV_VARS"
    set +a
  fi
  if [[ -z "${CLOUDFLARE_API_TOKEN:-}" || -z "${CLOUDFLARE_ACCOUNT_ID:-}" ]]; then
    CF_TOKEN="$(prompt_secret "   CLOUDFLARE_API_TOKEN (hidden, for wrangler auth): ")"
    CF_ACCOUNT="$(prompt "   CLOUDFLARE_ACCOUNT_ID: ")"
    export CLOUDFLARE_API_TOKEN="$CF_TOKEN"
    export CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT"
  fi
  if [[ -z "${CLOUDFLARE_API_TOKEN:-}" || -z "${CLOUDFLARE_ACCOUNT_ID:-}" ]]; then
    echo "error: Cloudflare credentials required to run wrangler secret put" >&2
    exit 1
  fi
fi
echo ""

if [[ "$MODE" == "local" ]]; then
  umask 077
  cat > "$DEV_VARS" <<EOF
# Generated by setup-secrets.sh — do not commit
TOSS_CLIENT_ID=${TOSS_ID}
TOSS_CLIENT_SECRET=${TOSS_SECRET}
CLOUDFLARE_API_TOKEN=${CF_TOKEN}
CLOUDFLARE_ACCOUNT_ID=${CF_ACCOUNT}
EOF
  chmod 600 "$DEV_VARS"

  # Inject account_id into wrangler.toml if placeholder / missing
  if grep -qE '^\s*#?\s*account_id\s*=' "$WRANGLER_TOML"; then
    # Replace commented or existing account_id line
    tmp="$(mktemp)"
    awk -v acc="$CF_ACCOUNT" '
      BEGIN { done=0 }
      /^[[:space:]]*#?[[:space:]]*account_id[[:space:]]*=/ && !done {
        print "account_id = \"" acc "\""
        done=1
        next
      }
      { print }
      END {
        if (!done) print "account_id = \"" acc "\""
      }
    ' "$WRANGLER_TOML" > "$tmp"
    mv "$tmp" "$WRANGLER_TOML"
  else
    printf '\naccount_id = "%s"\n' "$CF_ACCOUNT" >> "$WRANGLER_TOML"
  fi

  echo "Done (local)."
  echo "  wrote: $DEV_VARS (mode 600)"
  echo "  set account_id in wrangler.toml"
  echo "  next: cd cloudflare && npx wrangler dev"
  exit 0
fi

# ── remote: TOSS → Worker secrets ────────────────────────
if ! command -v npx >/dev/null 2>&1; then
  echo "error: npx required (Node.js)" >&2
  exit 1
fi

export CLOUDFLARE_API_TOKEN
export CLOUDFLARE_ACCOUNT_ID

put_secret() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "  skip $name (empty)"
    return 0
  fi
  printf '%s' "$value" | npx --yes wrangler secret put "$name" --config "$WRANGLER_TOML"
  echo "  put $name"
}

echo "Uploading TOSS secrets to Worker (values hidden)..."
if [[ -z "$TOSS_ID" ]]; then
  echo "  TOSS skipped — Worker will run Yahoo/default only"
else
  put_secret "TOSS_CLIENT_ID" "$TOSS_ID"
  put_secret "TOSS_CLIENT_SECRET" "$TOSS_SECRET"
fi

echo ""
echo "Done (remote)."
echo "  Cloudflare API token was NOT stored as a Worker secret (deploy-time only)."
echo "  next: ./scripts/deploy.sh   # when available"
