/**
 * Media column catalog (Naver news + outlet archives).
 * Used by _ingest.mjs to generate SEO-ready markdown.
 */
export const MEDIA_COLUMNS = [
  // ——— 2026 ———
  { date: "2026-02-23", media: "전자신문", folder: "AI", title: "인공지능 실체화와 능동형 에이전트, 노동의 종말인가?", topics: ["AI", "에이전트", "노동"], url: "https://www.etnews.com/20260223000100", featured: true, featured_rank: 1 },
  { date: "2026-02-09", media: "전자신문", folder: "AI", title: "미국 AI 빅테크, '돈 버는 AI'로의 전환을 선택하다", topics: ["AI", "빅테크", "버티컬AI"], url: "https://www.etnews.com/20260209000147", featured: true, featured_rank: 2 },
  { date: "2026-02-02", media: "전자신문", folder: "AI", title: "피지컬 AI 대중화 시대, '로봇계 샤오미' 유니트리를 주목하라", topics: ["피지컬AI", "유니트리", "로봇"], url: "https://www.etnews.com/20260202000393", featured: true, featured_rank: 3 },
  { date: "2026-01-26", media: "전자신문", folder: "Crypto-Stablecoin", title: "BitGo 상장의 의미-블록체인 인프라가 월가에 진출하다", topics: ["BitGo", "인프라", "월가"], url: "https://www.etnews.com/20260126000104", featured: false },
  { date: "2026-01-19", media: "전자신문", folder: "Crypto-Stablecoin", title: "STO 입법 통과, 이제 '규제 샌드박스'를 넘어 마켓으로", topics: ["STO", "규제", "토큰증권"], url: "https://www.etnews.com/20260119000138", featured: true, featured_rank: 8 },
  { date: "2026-01-12", media: "전자신문", folder: "Society-Culture", title: "인공지능 디지털 아티스트의 미래를 예지하다", topics: ["AI", "아트", "디지털아트"], url: "https://www.etnews.com/20260112000148", featured: false },

  // ——— 2025 late ———
  { date: "2025-12-15", media: "전자신문", folder: "Crypto-Stablecoin", title: "코인원 차명훈 대표의 경영복귀와 블록체인의 미래", topics: ["코인원", "거래소", "블록체인"], url: "https://www.etnews.com/20251215000226", featured: false },
  { date: "2025-12-08", media: "전자신문", folder: "Security", title: "해킹의 계절, 거래소와 재단 파고드는 사이버 위협과 생존", topics: ["업비트", "해킹", "라자루스"], url: "https://www.etnews.com/20251208000117", featured: true, featured_rank: 4 },
  { date: "2025-11-24", media: "전자신문", folder: "Crypto-Stablecoin", title: "비트코인 급락의 원인, MSCI 지수 퇴출 공포", topics: ["비트코인", "MSCI", "매크로"], url: "https://www.etnews.com/20251124000106", featured: true, featured_rank: 5 },
  { date: "2025-11-03", media: "전자신문", folder: "Macro-Policy", title: "'치맥 회동'이 보여준 반도체 전쟁의 새로운 지형", topics: ["반도체", "엔비디아", "삼성"], url: "https://www.etnews.com/20251103000180", featured: true, featured_rank: 6 },
  { date: "2025-10-27", media: "전자신문", folder: "Crypto-Stablecoin", title: "APEC과 FOMC, 가상화폐 시장의 '변곡점'을 맞이하다", topics: ["가상자산", "FOMC", "APEC"], url: "https://www.etnews.com/20251027000423", featured: false },
  { date: "2025-10-22", media: "전자신문", folder: "Crypto-Stablecoin", title: "가상화폐 거래소의 딜레마, 폭락 속에 드러난 거래소의 취약성", topics: ["거래소", "폭락", "인프라"], url: "", featured: false },
  { date: "2025-10-13", media: "전자신문", folder: "Crypto-Stablecoin", title: "트럼프가 쏘아 올린 작은 공, 가상자산 도박장에 경종을 울리다", topics: ["트럼프", "관세", "가상자산"], url: "https://www.etnews.com/20251013000241", featured: false },
  { date: "2025-09-29", media: "전자신문", folder: "Crypto-Stablecoin", title: "세계 3위 거래소 업비트 빅딜이 의미하는 네이버-두나무 핀테크", topics: ["업비트", "네이버", "두나무"], url: "https://www.etnews.com/20250929000321", featured: true, featured_rank: 7 },
  { date: "2025-09-23", media: "전자신문", folder: "Blockchain-P2E", title: "KBW 2025, 블록체인 위크가 주목해야 할 3가지 변화", topics: ["KBW", "블록체인"], url: "https://www.etnews.com/20250923000464", featured: false },
  { date: "2025-09-08", media: "전자신문", folder: "AI", title: "중국의 AI 굴기와 한국의 선택, 오픈소스 혁명이 가져온 기회", topics: ["중국AI", "오픈소스", "딥시크"], url: "https://www.etnews.com/20250908000392", featured: true, featured_rank: 9 },
  { date: "2025-09-01", media: "전자신문", folder: "Blockchain-P2E", title: "디지털 네이티브 시대, 블록체인 기술이 미술 시장의 신경회로가 되다", topics: ["NFT", "미술", "블록체인"], url: "", featured: false },
  { date: "2025-08-25", media: "전자신문", folder: "Crypto-Stablecoin", title: "해커에서 블록체인의 리더, 다음 도전을 시작하다-차명훈", topics: ["코인원", "차명훈"], url: "https://www.etnews.com/20250825000153", featured: false },
  { date: "2025-08-18", media: "전자신문", folder: "Crypto-Stablecoin", title: "원화 스테이블코인 시장, 규제 샌드박스로 독과점 시장에 도전하다", topics: ["스테이블코인", "원화", "샌드박스"], url: "https://www.etnews.com/20250818000068", featured: false },
  { date: "2025-07-25", media: "전자신문", folder: "Security", title: "악당의 하수인 해커들: 북한 해커의 '미니언즈' 신드롬과 대응", topics: ["북한", "해킹", "보안"], url: "", featured: false },
  { date: "2025-07-21", media: "전자신문", folder: "AI", title: "인공지능은 경제 공황을 예지할 수 있을까?", topics: ["AI", "공황", "금융"], url: "https://www.etnews.com/20250721000203", featured: false },
  { date: "2025-07-14", media: "전자신문", folder: "Crypto-Stablecoin", title: "알고리즘 스테이블코인의 저주: 테라-루나의 교훈과 한국의 선택", topics: ["테라", "스테이블코인", "규제"], url: "https://www.etnews.com/20250714000094", featured: true, featured_rank: 10 },
  { date: "2025-07-08", media: "전자신문", folder: "Crypto-Stablecoin", title: "갈라파고스에서 벗어나는 한국의 가상화폐 거래소, 법인·외국인 계정 재개", topics: ["거래소", "규제완화", "갈라파고스"], url: "https://www.etnews.com/20250708000001", featured: false },
  { date: "2025-06-30", media: "전자신문", folder: "AI", title: "소버린 AI, 글로벌 연대로 발전해야 한다", topics: ["소버린AI", "기술주권"], url: "https://www.etnews.com/20250630000141", featured: false },
  { date: "2025-06-26", media: "전자신문", folder: "Crypto-Stablecoin", title: "스테이블 코인의 미래-GENIUS Act 이후 한국의 기회와 도전", topics: ["GENIUS", "스테이블코인", "달러"], url: "https://www.etnews.com/20250626000177", featured: true, featured_rank: 11 },
  { date: "2025-06-16", media: "전자신문", folder: "Crypto-Stablecoin", title: "원화 스테이블코인이 허용되야 하는 이유", topics: ["원화", "스테이블코인"], url: "https://www.etnews.com/20250616000043", featured: false },
  { date: "2025-06-09", media: "전자신문", folder: "AI", title: "이재명 시대, 한국을 AI 3강으로 이끌 4대 전략 제언", topics: ["AI정책", "한국"], url: "https://www.etnews.com/20250609000142", featured: false },
  { date: "2025-05-23", media: "전자신문", folder: "AI", title: "구글의 인공지능 전략의 명암: 혁신과 격차 사이", topics: ["구글", "AI"], url: "https://www.etnews.com/20250523000081", featured: false },
  { date: "2025-05-21", media: "전자신문", folder: "Blockchain-P2E", title: "블록체인 기반 투표 시스템 통한 민주주의의 신뢰 회복", topics: ["투표", "블록체인", "민주주의"], url: "https://www.etnews.com/20250521000070", featured: false },
  { date: "2025-05-15", media: "전자신문", folder: "AI", title: "AI 코딩 시대, 시니어 개발자의 재발견", topics: ["바이브코딩", "시니어", "개발자"], url: "https://www.etnews.com/20250515000230", featured: true, featured_rank: 12 },
  { date: "2025-05-07", media: "전자신문", folder: "AI", title: "인공지능은 공공 기관의 낭비를 줄일 수 있을까?", topics: ["공공", "AI", "효율"], url: "https://www.etnews.com/20250507000379", featured: false },
  { date: "2025-04-28", media: "전자신문", folder: "AI", title: "바이브 코딩(Vibe Coding), 인공지능과의 페어 프로그래밍", topics: ["바이브코딩", "AI코딩"], url: "https://www.etnews.com/20250428000150", featured: false },
  { date: "2025-04-21", media: "전자신문", folder: "Security", title: "사이버 보안의 최전선, 셧다운 위기에서 살아나다", topics: ["보안", "셧다운"], url: "https://www.etnews.com/20250421000054", featured: false },
  { date: "2025-04-14", media: "전자신문", folder: "Crypto-Stablecoin", title: "스테이블코인의 혁명: USD1의 도전과 금융 미래의 재편", topics: ["USD1", "스테이블코인"], url: "https://www.etnews.com/20250414000067", featured: false },
  { date: "2025-04-07", media: "전자신문", folder: "Society-Culture", title: "인공지능은 자살이 우려되는 사람을 어떻게 찾고 살릴 수 있는가", topics: ["AI", "헬스케어", "자살예방"], url: "", featured: false },
  { date: "2025-04-02", media: "전자신문", folder: "AI", title: "인공지능 혁명은 왜 가난을 가속화 시킬까?", topics: ["AI", "불평등", "노동"], url: "https://www.etnews.com/20250402000138", featured: false },
  { date: "2025-03-24", media: "전자신문", folder: "AI", title: "미국 투자은행의 인력 감축으로 보는 인공지능 혁명과 경제", topics: ["투자은행", "AI", "고용"], url: "", featured: false },
  { date: "2025-03-17", media: "전자신문", folder: "Society-Culture", title: "김새론 배우의 죽음을 애도하며: 기술이 예지하고 막을 수 있었던 비극", topics: ["디지털폭력", "플랫폼"], url: "https://www.etnews.com/20250317000130", featured: false },
  { date: "2025-03-11", media: "전자신문", folder: "Blockchain-P2E", title: "블록체인과 AI가 국민연금 개혁의 갈등을 조정하는 법", topics: ["국민연금", "블록체인", "AI"], url: "https://www.etnews.com/20250311000058", featured: false },
  { date: "2025-03-04", media: "전자신문", folder: "AI", title: "AI vs. 월스트리트: 주식시장의 게임 체인저 인공지능", topics: ["AI", "월스트리트", "퀀트"], url: "https://www.etnews.com/20250304000237", featured: false },
  { date: "2025-02-24", media: "전자신문", folder: "Security", title: "세계 2위 바이빗 해킹 사태, 중국계 거래소 협력으로 유출된 교훈", topics: ["바이빗", "해킹", "거래소"], url: "https://www.etnews.com/20250224000052", featured: false },
  { date: "2025-02-21", media: "전자신문", folder: "Blockchain-P2E", title: "'홍콩 블록체인위크 2025' 회고: AI와 블록체인의 융합", topics: ["홍콩", "블록체인", "AI"], url: "https://www.etnews.com/20250221000150", featured: false },
  { date: "2025-02-18", media: "전자신문", folder: "Society-Culture", title: "배우 김새론의 비극을 계기로 본 디지털 사회를 위한 제안", topics: ["디지털사회", "플랫폼책임"], url: "", featured: false },
  { date: "2025-02-10", media: "전자신문", folder: "AI", title: "중국 AI의 경이로운 성장: '딥시크 쇼크'가 보여준 4가지", topics: ["딥시크", "중국AI"], url: "https://www.etnews.com/20250210000116", featured: false },
  { date: "2025-02-07", media: "전자신문", folder: "AI", title: "인공지능은 어떻게 인간의 거짓말을 예지하고 판단할 수 있는가", topics: ["AI", "탐지", "신뢰"], url: "", featured: false },
  { date: "2025-02-06", media: "전자신문", folder: "AI", title: "버티컬 AI의 시대: 팔란티어 100달러 돌파가 말해주는 투자 시사점", topics: ["버티컬AI", "팔란티어"], url: "", featured: false },
  { date: "2025-02-05", media: "전자신문", folder: "Macro-Policy", title: "트럼프의 중국 추가 관세 발표, 세 가지 관점으로 본 향후", topics: ["트럼프", "관세", "중국"], url: "https://www.etnews.com/20250205000081", featured: false },
  { date: "2025-02-04", media: "전자신문", folder: "Macro-Policy", title: "트럼프 관세 유예의 이면: 보호무역 강화와 글로벌 경제", topics: ["관세", "보호무역"], url: "https://www.etnews.com/20250204000117", featured: false },
  { date: "2025-02-03", media: "전자신문", folder: "Macro-Policy", title: "미·중 관세 전쟁 재점화, 여파는?", topics: ["미중", "관세"], url: "https://www.etnews.com/20250203000062", featured: false },
  { date: "2025-01-31", media: "전자신문", folder: "AI", title: "중국 AI 딥시크 쇼크: 미국 빅테크의 단기 고난과 중기 회복", topics: ["딥시크", "빅테크"], url: "https://www.etnews.com/20250131000029", featured: false },
  { date: "2025-01-23", media: "전자신문", folder: "Society-Culture", title: "ChatGPT로 예지하는 한국 영화의 미래", topics: ["ChatGPT", "영화", "AI"], url: "https://www.etnews.com/20250123000310", featured: false },
  { date: "2025-01-20", media: "전자신문", folder: "Crypto-Stablecoin", title: "트럼프 시대 블록체인 정책과 코인 시장 전망", topics: ["트럼프", "블록체인", "정책"], url: "https://www.etnews.com/20250120000147", featured: false },
  { date: "2025-01-14", media: "전자신문", folder: "Security", title: "영화 '이미테이션 게임'과 현대의 정보전: 보안이란 무엇인가", topics: ["정보전", "보안"], url: "https://www.etnews.com/20250114000126", featured: false },
  { date: "2025-01-06", media: "전자신문", folder: "Security", title: "신년, 보안을 지키는 새로운 시작", topics: ["보안", "신년"], url: "https://www.etnews.com/20250106000347", featured: false },
  { date: "2025-01-02", media: "전자신문", folder: "Macro-Policy", title: "권한대행의 선택과 내쉬 평형: 게임 이론으로 본 쌍특검", topics: ["게임이론", "정치"], url: "https://www.etnews.com/20250102000051", featured: false },

  // ——— 2024 ———
  { date: "2024-12-23", media: "전자신문", folder: "Security", title: "스타트업 보안, 선택이 아닌 필수", topics: ["스타트업", "보안"], url: "https://www.etnews.com/20241223000054", featured: false },
  { date: "2024-12-16", media: "전자신문", folder: "Society-Culture", title: "유튜브 추천 알고리즘의 비극", topics: ["유튜브", "알고리즘"], url: "https://www.etnews.com/20241216000220", featured: false },
  { date: "2024-12-09", media: "전자신문", folder: "Security", title: "텔레그램은 공직자가 삭제하더라도 알고 있다", topics: ["텔레그램", "프라이버시"], url: "https://www.etnews.com/20241209000117", featured: false },
  { date: "2024-12-04", media: "전자신문", folder: "Blockchain-P2E", title: "계엄령과 블록체인이 남긴 교훈", topics: ["블록체인", "민주주의"], url: "https://www.etnews.com/20241204000233", featured: false },
  { date: "2024-12-02", media: "전자신문", folder: "AI", title: "인공지능 헬스케어-초고령 사회의 돌파구", topics: ["헬스케어", "AI", "고령화"], url: "https://www.etnews.com/20241202000169", featured: false },
  { date: "2024-11-25", media: "전자신문", folder: "Crypto-Stablecoin", title: "트럼프 행정부의 가상화폐 정책 전망", topics: ["트럼프", "가상자산"], url: "https://www.etnews.com/20241125000033", featured: false },
  { date: "2024-11-22", media: "전자신문", folder: "Security", title: "가상자산 거래소 사칭 스미싱 메일 주의", topics: ["스미싱", "거래소"], url: "https://www.etnews.com/20241122000196", featured: false },
  { date: "2024-11-11", media: "전자신문", folder: "Macro-Policy", title: "트럼프 시대 인공지능과 블록체인 정책", topics: ["트럼프", "AI", "블록체인"], url: "https://www.etnews.com/20241111000322", featured: false },
  { date: "2024-11-04", media: "전자신문", folder: "AI", title: "인공지능이 만드는 농업의 미래", topics: ["농업", "AI"], url: "https://www.etnews.com/20241104000264", featured: false },
  { date: "2024-10-28", media: "전자신문", folder: "AI", title: "미국의 인공지능 전략과 국가 안보", topics: ["AI", "안보", "미국"], url: "https://www.etnews.com/20241028000140", featured: false },
  { date: "2024-10-21", media: "전자신문", folder: "AI", title: "인공지능과 로봇이 바꾸는 전쟁의 미래: 기회와 위험", topics: ["로봇", "전쟁", "AI"], url: "https://www.etnews.com/20241021000031", featured: false },
  { date: "2024-10-14", media: "전자신문", folder: "AI", title: "중도 탈락하는 CTO vs 실패하는 CTO", topics: ["CTO", "스타트업"], url: "https://www.etnews.com/20241014000336", featured: false },
  { date: "2024-10-07", media: "전자신문", folder: "AI", title: "BCI 기술의 미래: 감각과 질병 예방의 혁명, 그러나 인간성", topics: ["BCI", "뇌컴퓨터"], url: "", featured: false },
  { date: "2024-09-30", media: "전자신문", folder: "Security", title: "미국의 새로운 패스워드 관리 규칙과 그 필요성", topics: ["패스워드", "보안"], url: "https://www.etnews.com/20240930000099", featured: false },
  { date: "2024-09-23", media: "전자신문", folder: "Society-Culture", title: "미술 아트테크: 갤러리K 사례와 투자 위험성", topics: ["아트테크", "미술투자"], url: "https://www.etnews.com/20240923000070", featured: false },
  { date: "2024-09-20", media: "전자신문", folder: "AI", title: "인공지능과 인간 노동의 대체, 그리고 기본 소득의 필요성", topics: ["기본소득", "노동", "AI"], url: "https://www.etnews.com/20240920000032", featured: false },
  { date: "2024-09-10", media: "전자신문", folder: "AI", title: "여성 개발자가 인공지능 개발에 필요한 이유", topics: ["다양성", "AI", "개발자"], url: "https://www.etnews.com/20240910000119", featured: false },
  { date: "2024-09-02", media: "전자신문", folder: "Security", title: "북한은 왜 가상화폐 해킹에 몰두하는가?", topics: ["북한", "가상화폐", "해킹"], url: "https://www.etnews.com/20240902000136", featured: false },
  { date: "2024-08-19", media: "전자신문", folder: "Society-Culture", title: "인공지능의 그림자: '에일리언: 로물루스, 커버넌트'가 주는 경고", topics: ["영화", "AI윤리"], url: "https://www.etnews.com/20240819000067", featured: false },
  { date: "2024-08-02", media: "전자신문", folder: "Blockchain-P2E", title: "티몬, 위메프 사태를 보는 블록체인의 투명성", topics: ["이커머스", "블록체인", "투명성"], url: "https://www.etnews.com/20240802000048", featured: false },
  { date: "2024-07-22", media: "전자신문", folder: "Security", title: "마이크로소프트 클라우드의 실패인가?", topics: ["클라우드", "MS", "장애"], url: "https://www.etnews.com/20240722000182", featured: false },
  { date: "2024-07-15", media: "전자신문", folder: "Security", title: "일본의 사이버 공격 능동 대응: 전쟁이 가능한 보통 국가로", topics: ["일본", "사이버", "안보"], url: "https://www.etnews.com/20240715000091", featured: false },
  { date: "2024-07-04", media: "전자신문", folder: "AI", title: "개발자에게 학벌이 중요할까?", topics: ["개발자", "학벌", "채용"], url: "https://www.etnews.com/20240704000244", featured: false },
  { date: "2024-06-25", media: "전자신문", folder: "Security", title: "가상화폐 재단을 노리는 북한의 해킹", topics: ["북한", "재단", "해킹"], url: "https://www.etnews.com/20240625000097", featured: false },
  { date: "2024-06-13", media: "전자신문", folder: "AI", title: "애플이 바라보는 인공지능 프라이버시 보호의 미래", topics: ["애플", "프라이버시", "AI"], url: "https://www.etnews.com/20240613000345", featured: false },
  { date: "2024-06-10", media: "전자신문", folder: "AI", title: "ChatGPT 교육이 필요하다", topics: ["ChatGPT", "교육"], url: "https://www.etnews.com/20240610000016", featured: false },
  { date: "2024-05-30", media: "전자신문", folder: "AI", title: "AI가 지구 온난화를 가속화하고 있다", topics: ["AI", "기후", "에너지"], url: "https://www.etnews.com/20240530000350", featured: false },

  // ——— 2022 ———
  { date: "2022-10-23", media: "전자신문", folder: "Security", title: "블록체인 탈중앙화 금융 보안의 딜레마", topics: ["DeFi", "보안"], url: "", featured: false },
  { date: "2022-10-16", media: "전자신문", folder: "Blockchain-P2E", title: "카카오톡 장애를 바라보는 블록체인의 철학", topics: ["카카오", "탈중앙화"], url: "", featured: false },
  { date: "2022-10-12", media: "전자신문", folder: "Blockchain-P2E", title: "안전한 NFT 2차 거래 가이드라인", topics: ["NFT", "거래"], url: "", featured: false },
  { date: "2022-10-03", media: "전자신문", folder: "Crypto-Stablecoin", title: "루나 권도형은 왜 비트코인을 거래소로 송금했나?", topics: ["루나", "권도형"], url: "", featured: false },
  { date: "2022-10-03", media: "전자신문", folder: "Blockchain-P2E", title: "기업용 NFT 시장은 어떻게 접근해야 할까?", topics: ["NFT", "기업"], url: "", featured: false },
  { date: "2022-09-24", media: "전자신문", folder: "Blockchain-P2E", title: "메타콩즈의 이두희 사태의 본질과 해법", topics: ["메타콩즈", "NFT"], url: "", featured: false },
  { date: "2022-09-13", media: "전자신문", folder: "Blockchain-P2E", title: "P2E 산업, 공공의 적", topics: ["P2E", "규제"], url: "", featured: false },
  { date: "2022-09-05", media: "전자신문", folder: "Blockchain-P2E", title: "P2E의 대중화를 위한 법률 제언", topics: ["P2E", "법률"], url: "", featured: false },
  { date: "2022-09-02", media: "전자신문", folder: "Security", title: "윈도우를 먹통으로 만든 알약의 오류 사태와 보안", topics: ["알약", "보안사고"], url: "", featured: false },
  { date: "2022-08-29", media: "전자신문", folder: "Crypto-Stablecoin", title: "비트코인 왜 폭락했나?", topics: ["비트코인", "폭락"], url: "", featured: false },
  { date: "2022-08-24", media: "전자신문", folder: "Security", title: "빅테크 기업에게 개인 프라이버시는 있을까?", topics: ["프라이버시", "빅테크"], url: "", featured: false },
  { date: "2022-08-20", media: "전자신문", folder: "AI", title: "인공지능이 만드는 프로그램 개발의 혁신", topics: ["AI코딩", "개발"], url: "", featured: false },
  { date: "2022-08-17", media: "전자신문", folder: "Blockchain-P2E", title: "P2E에서 클레이튼의 가능성과 리스크", topics: ["클레이튼", "P2E"], url: "", featured: false },
  { date: "2022-08-15", media: "전자신문", folder: "Macro-Policy", title: "소프트뱅크 손정의의 실패에서 배우는 스타트업", topics: ["소프트뱅크", "스타트업"], url: "", featured: false },
  { date: "2022-08-11", media: "전자신문", folder: "Security", title: "러시아 랜섬웨어 조직으로 보는 스타트업 경영 기법", topics: ["랜섬웨어", "Conti"], url: "", featured: false },
  { date: "2022-08-04", media: "전자신문", folder: "Security", title: "사이버 전쟁은 시작되었다", topics: ["사이버전쟁", "안보"], url: "", featured: false },
  { date: "2022-07-25", media: "전자신문", folder: "Security", title: "가상화폐를 노리는 불량국가 북한", topics: ["북한", "가상화폐"], url: "", featured: false },
  { date: "2022-07-22", media: "전자신문", folder: "Blockchain-P2E", title: "P2E를 위한 블록체인 기술의 이해", topics: ["P2E", "블록체인"], url: "", featured: false },
  { date: "2022-07-11", media: "전자신문", folder: "Crypto-Stablecoin", title: "가상화폐 폭락이 기존 금융 시장을 흔들 수 있을까?", topics: ["가상화폐", "금융"], url: "", featured: false },
  { date: "2022-07-11", media: "전자신문", folder: "Blockchain-P2E", title: "P2E, 기회와 리스크", topics: ["P2E"], url: "", featured: false },
  { date: "2022-07-07", media: "전자신문", folder: "Security", title: "가상화폐 지갑을 사용할 때 주의점", topics: ["지갑", "보안"], url: "", featured: false },
  { date: "2022-06-18", media: "전자신문", folder: "Security", title: "SIM Swapping 공격을 당해본 후기", topics: ["SIM스와핑", "보안"], url: "", featured: false },
  { date: "2022-05-22", media: "전자신문", folder: "Blockchain-P2E", title: "메인넷의 어려움과 NFT의 미래", topics: ["메인넷", "NFT"], url: "", featured: false },
  { date: "2022-05-12", media: "전자신문", folder: "Crypto-Stablecoin", title: "LUNA 급락과 가상화폐 투자의 기회", topics: ["루나", "LUNA"], url: "", featured: false },
  { date: "2022-05-09", media: "전자신문", folder: "Crypto-Stablecoin", title: "비트코인 하락기를 어떻게 바라봐야 하나?", topics: ["비트코인"], url: "", featured: false },
  { date: "2022-04-26", media: "전자신문", folder: "Security", title: "스마트폰 유심에 비밀 번호를 설정하세요", topics: ["유심", "보안"], url: "", featured: false },
  { date: "2022-04-20", media: "전자신문", folder: "Blockchain-P2E", title: "메타콩즈 사태로 보는 NFT 해킹과 미래", topics: ["메타콩즈", "NFT해킹"], url: "", featured: false },

  // ——— ZDNet / older ———
  { date: "2020-02-25", media: "ZDNet Korea", folder: "Security", title: "코로나19 불안감 타고 증식하는 '스미싱'", topics: ["스미싱", "코로나"], url: "https://zdnet.co.kr/view/?no=20200225000000", featured: false },
  { date: "2020-02-21", media: "전자신문", folder: "Security", title: "개인 정보 보호를 위한 탈중앙화 아이디가 필요한 이유", topics: ["DID", "프라이버시"], url: "", featured: false },
  { date: "2019-07-19", media: "ZDNet Korea", folder: "Blockchain-P2E", title: "대기업 블록체인 참여와 '실체 의문' 해소", topics: ["블록체인", "대기업"], url: "https://zdnet.co.kr/view/?no=20190719085536", featured: false },
  { date: "2019-05-20", media: "ZDNet Korea", folder: "Security", title: "ICO 프로젝트, 사회 공학적 해킹에 대비하라", topics: ["ICO", "사회공학"], url: "https://zdnet.co.kr/view/?no=20190520235500", featured: false },
  { date: "2019-01-17", media: "ZDNet Korea", folder: "Blockchain-P2E", title: "중국 정부의 블록체인 규제와 블록체인의 미래", topics: ["중국", "규제", "블록체인"], url: "https://zdnet.co.kr/view/?no=20190117084935", featured: false },
  { date: "2018-12-29", media: "벤처스퀘어", folder: "Crypto-Stablecoin", title: "과연 시장에 비트코인은 있는가?", topics: ["비트코인"], url: "", featured: false },
  { date: "2018-11-09", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "블록체인, 유지보수라는 또다른 리스크", topics: ["메인넷", "유지보수"], url: "", featured: false },
  { date: "2018-10-16", media: "벤처스퀘어", folder: "Macro-Policy", title: "블록체인, 세상 바꿀 '파격적 입법' 필요하다", topics: ["입법", "블록체인"], url: "", featured: false },
  { date: "2018-10-04", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "'비트코인 제로데이'와 메인넷의 딜레마", topics: ["제로데이", "메인넷"], url: "", featured: false },
  { date: "2018-09-06", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "꿈의 기술 '블록체인 메인넷' 이뭐꼬?", topics: ["메인넷"], url: "", featured: false },
  { date: "2018-03-05", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "무너지는 금융·IT 경계…블록체인이 혁신인 이유", topics: ["금융", "블록체인"], url: "https://www.venturesquare.net/author/gameworker/", featured: false },
  { date: "2018-02-27", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "ICO 진행 중 느낀 '블록체인을 위한 클라우드'", topics: ["ICO", "클라우드"], url: "https://www.venturesquare.net/760229/", featured: false },
  { date: "2018-01-16", media: "벤처스퀘어", folder: "Crypto-Stablecoin", title: "버블과 투기 사이…가상화폐 논란", topics: ["버블", "가상화폐"], url: "", featured: false },
  { date: "2018-01-02", media: "벤처스퀘어", folder: "Blockchain-P2E", title: "게임 생태계와 블록체인이 만들 혁신", topics: ["게임", "블록체인"], url: "https://www.venturesquare.net/757947/", featured: false },
  { date: "2017-10-11", media: "ZDNet Korea", folder: "Blockchain-P2E", title: "블록체인은 어떻게 부정선거 시비 막을 수 있나", topics: ["선거", "블록체인"], url: "https://zdnet.co.kr/view/?no=20171011095837", featured: false },
  { date: "2016-03-28", media: "ZDNet Korea", folder: "Security", title: "핀테크, 머신러닝 기반 FDS를 주목해야할 이유", topics: ["FDS", "머신러닝", "핀테크"], url: "https://zdnet.co.kr/view/?no=20160328132520", featured: false },
  { date: "2014-10-06", media: "ZDNet Korea", folder: "Security", title: "진화하는 금융 사기, 제대로 예방하려면…", topics: ["금융사기", "보안"], url: "https://zdnet.co.kr/view/?no=20141006083136", featured: false },
  { date: "2014-07-28", media: "ZDNet Korea", folder: "Security", title: "잊혀질 권리를 찾는 법", topics: ["잊혀질권리", "프라이버시"], url: "https://zdnet.co.kr/view/?no=20140728101153", featured: false },
  { date: "2014-07-15", media: "ZDNet Korea", folder: "Security", title: "패스워드를 제대로 관리하는 방법", topics: ["패스워드", "보안"], url: "https://zdnet.co.kr/view/?no=20140715182038", featured: false },
];

export const FOLDER_GROUP = {
  AI: "media-ai",
  "Crypto-Stablecoin": "media-crypto",
  Security: "media-security",
  "Blockchain-P2E": "media-blockchain",
  "Macro-Policy": "media-macro",
  "Society-Culture": "media-society",
};
