name = "vibequant-engine-pdf"
main = "index.js"
compatibility_date = "2026-07-01"
account_id = "4bb6612c3a816c507ecc342d640d5da4"
workers_dev = false

[[routes]]
pattern = "vibequant.cc/files/engine-remembers-era.pdf"
zone_name = "vibequant.cc"
