import { TranslationKeys } from './types';

export const ko: TranslationKeys = {
  // Navbar
  'navbar.features': '기능',
  'navbar.benchmark': '벤치마크',
  'navbar.quickstart': '퀵스타트',
  'navbar.docs': '문서',
  'navbar.blog': '블로그',
  'navbar.getStarted': '시작하기',

  // Hero
  'hero.title': 'AI 코드 리뷰\n수백만 건의\n실무 작업으로 검증됨',
  'hero.description': 'Open Code Review는 알리바바에서 실전 검증된 코드 리뷰 에이전트를 여러분의 워크플로에 통합합니다. 어떤 LLM에도 연결하고, 데이터를 완전히 비공개로 유지하며, 개발자가 실제로 반영하는 리뷰 코멘트를 받아보세요.',
  'hero.quickStart': '퀵스타트',
  'hero.learnMore': '자세히 보기',
  'hero.terminal': '터미널',
  'hero.copied': '복사됨!',
  'hero.copyFailed': '복사 실패',

  // Highlights
  'highlights.stat1Value': '20K+',
  'highlights.stat1Label': '활성 사용자',
  'highlights.stat1Caption': '알리바바 그룹 내부에서 실전 검증됨',
  'highlights.stat2Value': '> 30%',
  'highlights.stat2Label': '채택률',
  'highlights.stat2Caption': '알리바바 그룹 내부에서 실전 검증됨',
  'highlights.stat3Value': '1M+',
  'highlights.stat3Label': '실무 작업',
  'highlights.stat3Caption': '실행된 코드 리뷰 작업',
  'highlights.stat4Value': '1/9',
  'highlights.stat4Label': '토큰 비용',
  'highlights.stat4Caption': 'Claude Code 대비 · 1,000 PR',
  'highlights.stat5Value': '25.10%',
  'highlights.stat5Label': 'AACR-BENCH',
  'highlights.stat5Caption': 'SEM.F1 벤치마크 점수',

  // Use Cases
  'usecases.sectionLabel': '사용 사례',
  'usecases.title': 'Open Code Review는 누구를 위한 것인가요?',
  'usecases.case1Title': '개인 개발자',
  'usecases.case1Desc': 'Open Code Review를 로컬 AI 지원 개발 워크플로에 내장하여 즉각적이고 높은 품질의 코드 리뷰 피드백을 받아보세요.',
  'usecases.case2Title': '플랫폼 팀',
  'usecases.case2Desc': '데이터 흐름과 리뷰 정책을 완전히 제어하면서 내부 시스템에 매끄럽게 통합하세요.',
  'usecases.case3Title': 'ML 연구자',
  'usecases.case3Desc': 'RL 학습 파이프라인의 코드 품질 검증기로 사용하여 코드 생성 모델에 신뢰할 수 있는 보상 신호를 제공하세요.',

  // Features
  'features.sectionBadge': '핵심 기능',
  'features.title': '코드 리뷰를 위해 설계된 에이전트 시스템',
  'features.subtitle': '파일을 읽고, 코드베이스를 검색하며, 컨텍스트를 상호 참조하고, 세밀한 규칙을 적용해 심층 리뷰를 수행하는 AI 에이전트입니다.',
  'features.feat1Title': '하이브리드 아키텍처: 결정적 처리 + 에이전트',
  'features.feat1Desc': '결정적 엔지니어링(작업 분할, 파일 필터링, 행 번호 위치 지정, 규칙 라우팅, 비동기 스케줄링)과 LLM 에이전트 추론(리스크 탐지, 컨텍스트 탐색, 문제 분류)을 분리합니다. 엔지니어링 모듈은 확실성을, 에이전트는 의미 해석을 담당하여 품질·토큰 비용·속도를 최적화합니다.',
  'features.feat2Title': '정밀한 코멘트 배치와 리플렉션',
  'features.feat2Desc': '독립적인 행 단위 코멘트 배치 모듈과 3단계 점진적 LLM 전략으로 각 코멘트를 정확한 행 번호에 배치합니다. 별도의 리플렉션 모듈이 환각과 지식 드리프트를 조기에 차단합니다.',
  'features.feat3Title': '멀티 모델 프로토콜 지원',
  'features.feat3Desc': 'Anthropic Messages API와 OpenAI Chat Completions API를 모두 지원합니다. Anthropic, OpenAI, DashScope, DeepSeek, Z.AI 등 사전 설정된 공급자를 기본 제공하여 즉시 사용할 수 있으며, 프라이빗 배포를 위한 사용자 정의 모델 엔드포인트도 지원합니다.',
  'features.feat4Title': '동적 병렬 처리',
  'features.feat4Desc': '설정 가능한 goroutine 워커(기본 8개)로 하위 작업을 동적으로 분할하여 병렬 리뷰합니다. 대규모 변경 집합도 신속하게 완료됩니다.',
  'features.feat5Title': '스마트 메모리 압축',
  'features.feat5Desc': '코드 리뷰 전용 메모리 압축 방식으로, 3단계 파티션(고정/압축/활성) 컨텍스트 관리를 통해 토큰 한도를 넘어 심층 리뷰를 실현합니다.',
  'features.feat6Title': '내장 리뷰 규칙',
  'features.feat6Desc': '대규모 실무 시나리오로 검증된 리뷰 규칙으로, Java, TypeScript, Go, Python, Kotlin, Rust, C++, C 등 10개 이상의 언어를 지원하며 NPE, 스레드 안전성, XSS, SQL 인젝션 등에 대한 전문 규칙을 갖추고 있습니다.',

  // Benchmark
  'benchmark.sectionLabel': '오픈 벤치마크',
  'benchmark.title': '80명 이상의 시니어 엔지니어가 교차 검증',
  'benchmark.subtitle': '인기 오픈소스 저장소 50개에서 선정한 실제 Pull Request 200건으로 구성된 실무 CodeReview 벤치마크로, 10개 프로그래밍 언어와 다양한 문제 유형, 다양한 변경 규모를 아우릅니다.',
  'benchmark.colRank': '순위',
  'benchmark.colModel': '모델',
  'benchmark.colSource': '출처',
  'benchmark.colF1': 'F1',
  'benchmark.colPrecision': '정밀도',
  'benchmark.colRecall': '재현율',
  'benchmark.colAvgTime': '평균 시간',
  'benchmark.colAvgToken': '평균 토큰',

  // QuickStart
  'quickstart.sectionLabel': '퀵스타트',
  'quickstart.title': '몇 분 만에 시작하기',
  'quickstart.subtitle': '복잡한 설정이 필요 없습니다. 선택한 LLM 공급자 외에는 어떤 서드파티 계정도 필요하지 않습니다.',
  'quickstart.step1Title': '설치',
  'quickstart.step1Desc': 'npm으로 명령어 하나로 전역 설치합니다.',
  'quickstart.step1Label1': '설치',
  'quickstart.step1Label2': '설치 확인',
  'quickstart.step2Title': '설정',
  'quickstart.step2Desc': 'LLM 공급자를 대화식으로 설정하거나 수동으로 구성합니다.',
  'quickstart.step2Label1': '대화식 설정 (권장)',
  'quickstart.step2Label2': '수동 설정 (대안)',
  'quickstart.step2Label3': '설정 확인',
  'quickstart.step3Title': '리뷰 실행',
  'quickstart.step3Desc': '첫 번째 코드 리뷰를 시작합니다.',
  'quickstart.step3Label1': '리뷰 명령어',
  'quickstart.commentReview': '# 현재 변경 사항 리뷰',
  'quickstart.commentBranch': '# 브랜치 간 diff 리뷰',
  'quickstart.commentCommit': '# 특정 커밋 리뷰',
  'quickstart.copied': '복사됨!',

  // Footer
  'footer.brand': 'Open Code Review',
  'footer.copyright': '© Copyright 2026. All rights reserved.',

  // Docs Page
  'docs.toc': '목차',
  'docs.install': '설치',
  'docs.config': 'ocr config',
  'docs.review': 'ocr review',
  'docs.scan': 'ocr scan',
  'docs.viewer': 'ocr viewer',
  'docs.mcp': 'MCP Server',
  'docs.env': 'Claude Code 통합',
  'docs.installTitle': '설치',
  'docs.installLabel': '설치',
  'docs.installVerifyLabel': '설치 확인',
  'docs.configTitle': '설정 및 검증',
  'docs.configDesc': '통합된 공급자(Provider) 시스템을 통해 CLI 설정을 관리합니다. 다양한 내장 공급자를 제공하며 프라이빗 배포를 위한 사용자 정의 공급자도 지원합니다. 설정은 <code>~/.opencodereview/config.json</code>에 저장됩니다.',
  'docs.configInteractive': '대화식 설정 (권장)',
  'docs.configInteractiveDesc': 'Open Code Review를 설정하는 가장 쉬운 방법입니다. 내장 공급자 중 하나를 선택하거나 사용자 정의 공급자를 추가하고, API 키를 설정한 뒤 모델을 고릅니다.',
  'docs.configModelSelect': '모델 선택',
  'docs.configModelSelectDesc': '공급자를 선택한 후 사용할 모델을 고릅니다.',
  'docs.configListProviders': '내장 공급자 목록',
  'docs.configListProvidersDesc': '사용 가능한 모든 내장 LLM 공급자를 표시합니다.',
  'docs.configManual': '수동 설정',
  'docs.configManualBuiltin': '내장 공급자 사용',
  'docs.configManualBuiltinDesc': '내장 공급자에는 API URL과 프로토콜이 미리 설정되어 있으므로 API 키만 제공하면 됩니다.',
  'docs.configManualCustom': '사용자 정의 공급자 사용',
  'docs.configManualCustomDesc': '프라이빗 배포 또는 기타 호환 엔드포인트에 연결합니다.',
  'docs.configManualCustomNote': '사용자 정의 공급자에는 url과 protocol이 필수입니다. 지원 프로토콜: anthropic, openai.',
  'docs.configKeys': '지원되는 설정 키',
  'docs.configKeyProvider': '활성 공급자 이름',
  'docs.configKeyProviderApiKey': '공급자의 API 키',
  'docs.configKeyProviderModel': '모델 이름',
  'docs.configKeyProviderUrl': 'API URL 재정의',
  'docs.configKeyProviderExtraBody': '사용자 정의 요청 본문 필드 (JSON)',
  'docs.configKeyProviderExtraHeaders': '사용자 정의 HTTP 헤더 (key=value)',
  'docs.configKeyLanguage': '출력 언어',
  'docs.configKeyTelemetry': '텔레메트리',
  'docs.configVerify': '설정 확인',
  'docs.configVerifyDesc': '설정 후 이 명령어를 실행하여 LLM 연결을 테스트하고 설정이 올바른지 확인합니다.',
  'docs.reviewTitle': 'ocr review',
  'docs.reviewDesc': '<code>ocr review</code>는 AI 코드 리뷰를 시작하는 핵심 명령어입니다.',
  'docs.reviewModes': '리뷰 모드',
  'docs.reviewWorkspace': '작업공간 모드 (기본값)',
  'docs.reviewWorkspaceDesc': '현재 작업공간의 스테이지된 + 스테이지되지 않은 + 추적되지 않은 변경 사항을 리뷰합니다.',
  'docs.reviewBranch': '브랜치 diff 모드',
  'docs.reviewBranchDesc': '두 참조(ref) 사이의 diff를 리뷰합니다 (merge-base 기준).',
  'docs.reviewCommit': '단일 커밋 모드',
  'docs.reviewCommitDesc': '특정 커밋을 리뷰합니다 (부모 커밋과의 diff).',
  'docs.reviewAdvanced': '고급 사용법',
  'docs.reviewBackground': '요구사항 컨텍스트와 함께 리뷰',
  'docs.reviewBackgroundDesc': '요구사항 컨텍스트(중요한 경계 조건 포함)를 제공하여 리뷰 품질을 향상시킵니다.',
  'docs.reviewJson': 'JSON 출력',
  'docs.reviewJsonDesc': '구조화된 JSON 형식으로 결과를 출력하여 프로그램적 처리를 지원합니다.',
  'docs.reviewAgent': '에이전트 모드',
  'docs.reviewAgentDesc': '실행 과정 없이 최종 요약만 출력하며, 자동화 파이프라인에 적합합니다.',
  'docs.reviewPreviewLabel': 'Dry-Run 미리보기',
  'docs.reviewPreviewDesc': '리뷰 대상 파일 목록과 통계(파일 수, 변경된 행 수)를 표시합니다. LLM 호출도, 비용도 없습니다. 전체 리뷰 전에 범위를 확인하는 데 유용합니다.',
  'docs.reviewFlags': '플래그 레퍼런스',
  'docs.reviewFlagCol1': '플래그',
  'docs.reviewFlagCol2': '설명',
  'docs.reviewFlagCol3': '기본값',
  'docs.reviewFlag1Desc': '리뷰할 커밋 해시 지정',
  'docs.reviewFlag2Desc': '시작 참조 (diff 기점)',
  'docs.reviewFlag3Desc': '대상 참조 (diff 종점)',
  'docs.reviewFlag4Desc': '출력 형식: text 또는 json',
  'docs.reviewFlag5Desc': 'Git 저장소 루트',
  'docs.reviewFlag5Default': '현재 디렉터리',
  'docs.reviewFlag6Desc': '리뷰 규칙 JSON 파일 경로',
  'docs.reviewFlag6Default': '내장',
  'docs.reviewFlag7Desc': '최대 동시 파일 리뷰 수',
  'docs.reviewFlag8Desc': '단일 작업 타임아웃 (분)',
  'docs.reviewFlag9Desc': '출력 대상: human(과정 표시) 또는 agent(요약만)',
  'docs.reviewFlag10Desc': '파일당 최대 도구 호출 라운드 수. 템플릿 기본값보다 클 때만 적용됩니다',
  'docs.reviewFlag10Default': '내장',
  'docs.reviewFlag11Desc': '최대 동시 git 하위 프로세스 수',
  'docs.reviewNote': '참고: <code>--from/--to</code>와 <code>--commit</code>은 함께 사용할 수 없습니다. <code>--from</code>을 지정할 경우 <code>--to</code>도 반드시 지정해야 합니다.',
  'docs.scanTitle': 'ocr scan',
  'docs.scanDesc': '<code>ocr scan</code>은 diff 대신 파일 전체를 리뷰합니다. Git 이력이나 의미 있는 diff가 필요하지 않습니다. 낯선 코드베이스를 점검하거나, 마이그레이션 전에 디렉터리를 훑어보거나, diff 대상이 없는 프로젝트를 리뷰할 때 사용합니다.',
  'docs.scanVsTitle': 'ocr scan과 ocr review의 차이',
  'docs.scanVsReviewLabel': 'ocr review',
  'docs.scanVsReview': '<code>ocr review</code>는 diff 기반입니다. 작업공간의 스테이지된/스테이지되지 않은/추적되지 않은 변경, 브랜치 범위, 또는 단일 커밋 등 Git 변경 사항을 리뷰합니다. diff를 계산하려면 Git 이력이 필요합니다.',
  'docs.scanVsScanLabel': 'ocr scan',
  'docs.scanVsScan': '<code>ocr scan</code>은 파일 전체 기반입니다. Git 이력과 무관하게 파일의 전체 내용을 리뷰합니다. 비 git 디렉터리에서도 동작하며, 이 경우 .gitignore를 반영한 파일시스템 순회로 폴백합니다.',
  'docs.scanUsage': '기본 사용법',
  'docs.scanUsageWhole': '저장소 전체 스캔',
  'docs.scanUsageWholeDesc': '--path를 지정하지 않았을 때의 기본 동작입니다.',
  'docs.scanUsagePath': '특정 경로 스캔',
  'docs.scanUsagePathDesc': '저장소 기준 상대 디렉터리를 지정하여 스캔 범위를 좁힙니다.',
  'docs.scanUsageFile': '특정 파일 스캔',
  'docs.scanUsageFileDesc': '쉼표로 구분된 여러 파일 경로도 사용할 수 있습니다.',
  'docs.scanUsagePreviewLabel': 'Dry-Run 미리보기',
  'docs.scanUsagePreviewDesc': '범위 내 모든 파일을 나열하고 통계(전체 파일 수, 리뷰 가능/제외 수와 사유, 총 행 수)를 보고합니다. LLM 호출도, 비용도 없습니다. 큰 저장소에서 토큰을 소비하기 전에 범위를 확인하는 데 유용합니다.',
  'docs.scanBatching': '배치 처리 전략',
  'docs.scanBatchingDesc': '<code>--batch</code> 플래그는 파일이 리뷰 배치로 그룹화되는 방식을 제어합니다. 스캔 템플릿의 기본값은 <code>by-language</code>이며, 비어 있거나 인식할 수 없는 값은 <code>none</code>으로 폴백합니다.',
  'docs.scanBatchingNone': 'none',
  'docs.scanBatchingNoneDesc': '각 파일이 개별 배치가 됩니다. 그룹화가 없습니다.',
  'docs.scanBatchingLang': 'by-language',
  'docs.scanBatchingLangDesc': '파일 확장자(소문자화)를 기준으로 그룹화됩니다. 템플릿 기본값입니다.',
  'docs.scanBatchingDir': 'by-directory',
  'docs.scanBatchingDirDesc': '저장소 루트 바로 아래의 1차 디렉터리를 기준으로 그룹화됩니다. 루트 바로 아래 파일은 각각 개별 배치가 됩니다.',
  'docs.scanToggles': '스테이지 토글: --no-plan, --no-dedup, --no-summary',
  'docs.scanTogglesDesc': '스캔 실행에는 핵심 파일 단위 리뷰 외에 3개의 선택적 스테이지가 있습니다. 각 스테이지는 개별적으로 비활성화하여 리뷰 품질과 속도·토큰 비용을 절충할 수 있습니다.',
  'docs.scanTogglesPlanDesc': '메인 리뷰 전에 집중 영역을 정하는 파일 단위 PLAN_TASK 사전 처리를 건너뜁니다. 파일당 LLM 호출을 1회 절약하지만 리뷰 집중도가 낮아질 수 있습니다.',
  'docs.scanTogglesDedupDesc': '배치 단위 DEDUP_TASK를 건너뜁니다. 일반적으로 중복 제거로 병합되는 유사 코멘트를 포함해 모든 원본 코멘트를 유지합니다.',
  'docs.scanTogglesSummaryDesc': '실행 후 PROJECT_SUMMARY_TASK(모든 배치 완료 후 생성되는 저장소 단위 markdown 요약)를 건너뜁니다.',
  'docs.scanBudget': '토큰 예산: --max-tokens-budget',
  'docs.scanBudgetDesc': '디스패치 전에 <code>ocr scan</code>은 대략적인 토큰 비용 추정치를 출력합니다. <code>--max-tokens-budget</code>은 LLM API가 보고하는 입력+출력 토큰 총 사용량을 제한합니다. 누적 사용량이 상한을 초과하면 다음 배치를 시작하기 전에 디스패치가 중지됩니다. 기본값 <code>0</code>은 무제한을 의미합니다.',
  'docs.scanFlags': '플래그 레퍼런스',
  'docs.scanFlagCol1': '플래그',
  'docs.scanFlagCol2': '설명',
  'docs.scanFlagCol3': '기본값',
  'docs.scanFlag1Desc': '쉼표로 구분된 저장소 기준 상대 디렉터리/파일',
  'docs.scanFlag1Default': '저장소 전체',
  'docs.scanFlag2Desc': '쉼표로 구분된 gitignore 형식 제외 패턴. rule.json의 excludes와 병합됩니다',
  'docs.scanFlag3Desc': 'LLM을 실행하지 않고 스캔 대상 파일을 미리 봅니다',
  'docs.scanFlag4Desc': '토큰 총 사용량(입력+출력)을 제한. 초과 시 디스패치 중지 (0 = 무제한)',
  'docs.scanFlag5Desc': '파일 단위 PLAN_TASK 사전 처리를 건너뜁니다',
  'docs.scanFlag6Desc': '배치 단위 DEDUP_TASK를 건너뜁니다',
  'docs.scanFlag7Desc': '실행 후 PROJECT_SUMMARY_TASK를 건너뜁니다',
  'docs.scanFlag8Desc': '배치 처리 전략: none | by-language | by-directory',
  'docs.scanFlag9Desc': '출력 형식: text 또는 json',
  'docs.scanFlag10Desc': '최대 동시 파일 스캔 수',
  'docs.scanFlag11Desc': '동시 작업 타임아웃 (분)',
  'docs.scanFlag12Desc': '출력 대상: human(진행 표시) 또는 agent(요약만)',
  'docs.scanFlag13Desc': '스캔을 위한 선택적 요구사항·업무 배경 정보',
  'docs.scanFlag14Desc': '파일당 최대 도구 호출 라운드 수. 템플릿 기본값보다 클 때만 적용됩니다',
  'docs.scanFlag14Default': '내장',
  'docs.scanFlag15Desc': '최대 동시 git 하위 프로세스 수',
  'docs.scanFlag16Desc': '사용자 정의 JSON 리뷰 규칙 경로',
  'docs.scanFlag17Desc': '사용자 정의 JSON 도구 설정 경로',
  'docs.scanFlag17Default': '내장',
  'docs.scanFlag18Desc': '스캔할 저장소 또는 디렉터리 루트',
  'docs.scanFlag18Default': '현재 디렉터리',
  'docs.scanNote': '참고: <code>--max-tools</code>는 스캔 템플릿의 파일 단위 도구 호출 예산을 높일 때만 효과가 있습니다. 템플릿 기본값보다 낮게 설정하면 효과가 없습니다.',
  'docs.viewerTitle': 'ocr viewer',
  'docs.viewerDesc': '웹 인터페이스에서 리뷰 세션 로그를 열람할 수 있는 WebUI 세션 뷰어를 시작합니다.',
  'docs.viewerNote': '실행 후 로컬 HTTP 서버가 시작되어 리뷰 세션 로그를 열람할 수 있는 시각적 인터페이스를 제공합니다.',
  'docs.mcpTitle': 'MCP Server',
  'docs.mcpDesc': 'Open Code Review는 Model Context Protocol (MCP) 서버를 지원하여, 리뷰 에이전트가 stdio transport를 통해 코드 리뷰 중 외부 도구를 사용할 수 있습니다.',
  'docs.mcpConfig': 'MCP 서버 설정',
  'docs.mcpConfigLocation': 'MCP 서버 설정은 ~/.opencodereview/config.json에 저장됩니다.',
  'docs.mcpDelete': 'MCP 서버 삭제',
  'docs.mcpFields': '설정 필드',
  'docs.mcpFieldCol': '필드',
  'docs.mcpRequiredCol': '필수',
  'docs.mcpDescCol': '설명',
  'docs.mcpYes': '예',
  'docs.mcpNo': '아니오',
  'docs.mcpFieldCommandDesc': 'MCP 서버를 시작하는 실행 명령어',
  'docs.mcpFieldArgsDesc': '서버에 전달되는 명령줄 인수',
  'docs.mcpFieldEnvDesc': 'KEY=VALUE 형식의 환경 변수',
  'docs.mcpFieldToolsDesc': '허용할 도구 이름. 비어 있으면 서버가 제공하는 모든 도구를 사용할 수 있습니다',
  'docs.mcpFieldSetupDesc': '서버 시작 전에 실행할 shell 명령어. 예: 인덱스 구축',
  'docs.mcpNote': 'MCP 도구 이름이 내장 도구와 충돌하면 해당 도구는 경고와 함께 건너뜁니다. setup 명령어의 타임아웃은 5분입니다.',
  'docs.mcpExample': '예: CodeGraph를 추가하여 코드 구조 분석',
  'docs.envTitle': 'Claude Code 통합',
  'docs.envDesc': '이미 Claude Code 사용자이며 다음 환경 변수를 설정해 두었다면, Open Code Review가 자동으로 인식합니다. 추가 설정이 필요하지 않습니다:',
  'docs.envNote': '<code>ocr config</code>를 사용하여 이러한 설정을 재정의하거나 보완할 수도 있습니다.',
  'docs.copy': '복사',

  // Docs Sidebar
  'docs.sidebar.gettingStarted': '시작하기',
  'docs.sidebar.userGuide': '사용 가이드',
  'docs.sidebar.quickstart': '퀵스타트',
  'docs.sidebar.installation': '설치',
  'docs.sidebar.configuration': '설정',
  'docs.sidebar.cliReference': 'CLI 레퍼런스',
  'docs.sidebar.reviewRules': '리뷰 규칙',
  'docs.sidebar.architecture': '아키텍처',
  'docs.sidebar.tools': '도구',
  'docs.sidebar.mcp': 'MCP 서버',
  'docs.sidebar.viewer': '세션 뷰어',
  'docs.sidebar.telemetry': '텔레메트리',
  'docs.sidebar.integrations': '통합',
  'docs.sidebar.agentSkill': 'Agent Skill',
  'docs.sidebar.claudeCode': 'Command (Claude Code)',
  'docs.sidebar.subprocess': 'Direct Subprocess',
  'docs.sidebar.cicd': 'CI/CD',
  'docs.sidebar.contributing': '기여하기',
  'docs.sidebar.faq': 'FAQ',
  'docs.search.placeholder': '검색...',
  'docs.search.noResults': '결과를 찾을 수 없습니다',
  'docs.search.hint.select': '선택',
  'docs.search.hint.open': '열기',
  'docs.search.hint.close': '닫기',

  // Blog
  'blog.title': '블로그',
  'blog.allTags': '전체',
  'blog.backToList': '← 블로그로 돌아가기',
  'blog.toc': '목차',
  'blog.noPosts': '아직 게시물이 없습니다.',
  'blog.noPostsForTag': '이 태그에 해당하는 게시물이 없습니다.',
  'blog.search.placeholder': '게시물 검색...',
  'blog.search.noResults': '결과를 찾을 수 없습니다',
};
