/* generated by deploy.sh — do not edit by hand */
window.VIBEQUANT_API_BASE = "https://vibequant-api.YOUR_SUBDOMAIN.workers.dev";
window.VIBEQUANT_CDN_BASE = "https://vibequant-api.YOUR_SUBDOMAIN.workers.dev/cdn";
