/* generated by cloudflare/scripts/deploy.sh — do not edit by hand */
window.RUNTIME_CONFIG = {
  "VIBEQUANT_API_BASE": "https://vibequant-api.gameworker-4bb.workers.dev",
  "VIBEQUANT_CDN_BASE": "https://vibequant-api.gameworker-4bb.workers.dev/cdn"
};
window.VIBEQUANT_API_BASE = window.RUNTIME_CONFIG.VIBEQUANT_API_BASE;
window.VIBEQUANT_CDN_BASE = window.RUNTIME_CONFIG.VIBEQUANT_CDN_BASE;
